/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const API_BASE: typeof import('./lib/constants').API_BASE
  const Activity: typeof import('react').Activity
  const BOX_COLORS: typeof import('./lib/constants').BOX_COLORS
  const BULK_IMAGE_THRESHOLD: typeof import('./lib/processImageFiles').BULK_IMAGE_THRESHOLD
  const BatchProgress: typeof import('./components/BatchProgress/index').BatchProgress
  const CANVAS_MAX_H: typeof import('./lib/constants').CANVAS_MAX_H
  const CANVAS_MAX_W: typeof import('./lib/constants').CANVAS_MAX_W
  const CANVAS_MIN_BOX_SIZE: typeof import('./lib/constants').CANVAS_MIN_BOX_SIZE
  const CandidateListItem: typeof import('./components/Training/CandidateListItem/index').CandidateListItem
  const CategoryInput: typeof import('./components/CategoryInput/index').CategoryInput
  const CompareConfigPanel: typeof import('./components/Compare/CompareConfigPanel').CompareConfigPanel
  const CompareImageList: typeof import('./components/Compare/CompareImageList').CompareImageList
  const CompareLabelMapping: typeof import('./components/Compare/CompareLabelMapping').CompareLabelMapping
  const CompareMain: typeof import('./components/Compare/CompareMain').CompareMain
  const CompareProvider: typeof import('./components/Compare/CompareContext').CompareProvider
  const CompareReportCases: typeof import('./components/Compare/CompareReportCases').CompareReportCases
  const CompareReportPanel: typeof import('./components/Compare/CompareReportPanel').CompareReportPanel
  const CompareSidebar: typeof import('./components/Compare/CompareSidebar').CompareSidebar
  const CompareView: typeof import('./components/Compare/CompareView').CompareView
  const DEFAULT_BATCH: typeof import('./lib/constants').DEFAULT_BATCH
  const DEFAULT_CONF: typeof import('./lib/constants').DEFAULT_CONF
  const DEFAULT_EPOCHS: typeof import('./lib/constants').DEFAULT_EPOCHS
  const DEFAULT_IMGSZ: typeof import('./lib/constants').DEFAULT_IMGSZ
  const DEFAULT_IOU: typeof import('./lib/constants').DEFAULT_IOU
  const DEFAULT_TIMEOUT: typeof import('./services/request').DEFAULT_TIMEOUT
  const DETECT_TIMEOUT: typeof import('./services/request').DETECT_TIMEOUT
  const DatasetImportModal: typeof import('./components/DatasetImportModal/index').DatasetImportModal
  const DetectionCanvas: typeof import('./components/DetectionCanvas/index').DetectionCanvas
  const DetectionControls: typeof import('./components/Sidebar/DetectionControls').DetectionControls
  const DetectionResult: typeof import('./components/DetectionResult/index').DetectionResult
  const DetectionSkeleton: typeof import('./components/LoadingSkeleton/index').DetectionSkeleton
  const ErrorBoundary: typeof import('./components/ErrorBoundary/index').ErrorBoundary
  const ExtractionPanel: typeof import('./components/VideoPanel/ExtractionPanel').ExtractionPanel
  const FilterPanel: typeof import('./components/FilterPanel/index').FilterPanel
  const Fragment: typeof import('react').Fragment
  const HistoryList: typeof import('./components/HistoryList/index').HistoryList
  const HistoryListItem: typeof import('./components/HistoryListItem/index').HistoryListItem
  const HistorySkeleton: typeof import('./components/LoadingSkeleton/index').HistorySkeleton
  const Home: typeof import('./pages/Home').Home
  const HoverPreview: typeof import('./components/Training/HoverPreview/index').HoverPreview
  const ImageUploader: typeof import('./components/ImageUploader/index').ImageUploader
  const JobHistoryList: typeof import('./components/Training/JobHistoryList/index').JobHistoryList
  const KeyframeGrid: typeof import('./components/KeyframeGrid/index').KeyframeGrid
  const Layout: typeof import('./components/Layout/index').Layout
  const MAX_UPLOAD_SIZE_MB: typeof import('./lib/constants').MAX_UPLOAD_SIZE_MB
  const MetricLink: typeof import('./components/Compare/CompareReportCases').MetricLink
  const ModelSelector: typeof import('./components/ModelSelector/index').ModelSelector
  const ModelStatus: typeof import('./components/ModelStatus/index').ModelStatus
  const QueryClient: typeof import('@tanstack/react-query').QueryClient
  const QueryClientProvider: typeof import('@tanstack/react-query').QueryClientProvider
  const REPORT_TIMEOUT: typeof import('./services/request').REPORT_TIMEOUT
  const ResultTable: typeof import('./components/ResultTable/index').ResultTable
  const Sam3Status: typeof import('./components/Sam3Status/index').Sam3Status
  const Sidebar: typeof import('./components/Sidebar/index').Sidebar
  const SidebarHeader: typeof import('./components/Sidebar/Header').SidebarHeader
  const StatusBadge: typeof import('./components/Training/StatusBadge/index').StatusBadge
  const Suspense: typeof import('react').Suspense
  const ThemeContext: typeof import('./hooks/useTheme').ThemeContext
  const ThemeProvider: typeof import('./components/ThemeProvider/index').ThemeProvider
  const TrainingCandidateList: typeof import('./components/Training/TrainingCandidateList/index').TrainingCandidateList
  const TrainingJobItem: typeof import('./components/Training/TrainingJobItem/index').TrainingJobItem
  const TrainingPanel: typeof import('./components/TrainingPanel/index').TrainingPanel
  const TrainingPreview: typeof import('./components/Training/TrainingPreview/index').TrainingPreview
  const UPLOAD_TIMEOUT: typeof import('./services/request').UPLOAD_TIMEOUT
  const ValidationSettings: typeof import('./components/ValidationSettings/index').ValidationSettings
  const VideoDetail: typeof import('./components/VideoDetail/index').VideoDetail
  const VideoList: typeof import('./components/VideoPanel/VideoList').VideoList
  const VideoPanel: typeof import('./components/VideoPanel/index').VideoPanel
  const VideoValidator: typeof import('./components/VideoValidator/index').VideoValidator
  const addBox: typeof import('./services/api').addBox
  const applyFilter: typeof import('./lib/filterBoxes').applyFilter
  const autoMapByName: typeof import('./lib/compareLabelMap').autoMapByName
  const batchFileMap: typeof import('./lib/cache').batchFileMap
  const buildCompareReportHtml: typeof import('./lib/compareReportHtml').buildCompareReportHtml
  const buildPreviewUrls: typeof import('./lib/processImageFiles').buildPreviewUrls
  const buildReportThumbnails: typeof import('./lib/compareReportThumbnails').buildReportThumbnails
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cancelComparePrecompute: typeof import('./services/api').cancelComparePrecompute
  const cancelImport: typeof import('./services/api').cancelImport
  const cancelTrainingJob: typeof import('./services/api').cancelTrainingJob
  const caseFilterLabel: typeof import('./lib/compareReportCases').caseFilterLabel
  const chartUrl: typeof import('./services/api').chartUrl
  const checkSam3Health: typeof import('./services/api').checkSam3Health
  const clearCompareVlmCache: typeof import('./services/api').clearCompareVlmCache
  const collectDroppedFiles: typeof import('./lib/droppedFiles').collectDroppedFiles
  const compareImageUrl: typeof import('./services/api').compareImageUrl
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const deleteAllDetections: typeof import('./services/api').deleteAllDetections
  const deleteAllVideos: typeof import('./services/api').deleteAllVideos
  const deleteBox: typeof import('./services/api').deleteBox
  const deleteDetection: typeof import('./services/api').deleteDetection
  const deleteTrainingJob: typeof import('./services/api').deleteTrainingJob
  const deleteVideo: typeof import('./services/api').deleteVideo
  const detectImage: typeof import('./services/api').detectImage
  const downloadBlob: typeof import('./services/api').downloadBlob
  const downloadCompareReportHtml: typeof import('./lib/compareReportHtml').downloadCompareReportHtml
  const downloadDatasetUrl: typeof import('./services/api').downloadDatasetUrl
  const downloadModelUrl: typeof import('./services/api').downloadModelUrl
  const downloadOnnxUrl: typeof import('./services/api').downloadOnnxUrl
  const downloadYoloTxt: typeof import('./lib/yoloExport').downloadYoloTxt
  const exportBatch: typeof import('./services/api').exportBatch
  const exportCompareVlmDataset: typeof import('./services/api').exportCompareVlmDataset
  const exportSingleUrl: typeof import('./services/api').exportSingleUrl
  const extractKeyframes: typeof import('./services/api').extractKeyframes
  const fetchAnnotations: typeof import('./services/api').fetchAnnotations
  const fetchCompareDatasets: typeof import('./services/api').fetchCompareDatasets
  const fetchCompareReport: typeof import('./services/api').fetchCompareReport
  const fetchDatasetImages: typeof import('./services/api').fetchDatasetImages
  const fetchImportProgress: typeof import('./services/api').fetchImportProgress
  const fetchTrainingJobs: typeof import('./services/api').fetchTrainingJobs
  const fetchYoloSeries: typeof import('./services/api').fetchYoloSeries
  const fileUrlCache: typeof import('./lib/cache').fileUrlCache
  const filterImageFiles: typeof import('./lib/droppedFiles').filterImageFiles
  const filterReportCases: typeof import('./lib/compareReportCases').filterReportCases
  const formatTime: typeof import('./lib/formatTime').formatTime
  const forwardRef: typeof import('react').forwardRef
  const generateYoloTxt: typeof import('./lib/yoloExport').generateYoloTxt
  const getDetection: typeof import('./services/api').getDetection
  const getFileUrl: typeof import('./lib/cache').getFileUrl
  const getModelStatus: typeof import('./services/api').getModelStatus
  const getSam2Status: typeof import('./services/api').getSam2Status
  const getVideo: typeof import('./services/api').getVideo
  const importChunkCancel: typeof import('./services/api').importChunkCancel
  const importChunkComplete: typeof import('./services/api').importChunkComplete
  const importChunkInit: typeof import('./services/api').importChunkInit
  const importDataset: typeof import('./services/api').importDataset
  const isImageFile: typeof import('./lib/droppedFiles').isImageFile
  const keyframeImageUrl: typeof import('./services/api').keyframeImageUrl
  const lazy: typeof import('react').lazy
  const listDetections: typeof import('./services/api').listDetections
  const listVideos: typeof import('./services/api').listVideos
  const mapVlmBoxClass: typeof import('./lib/compareLabelMap').mapVlmBoxClass
  const mapVlmBoxes: typeof import('./lib/compareLabelMap').mapVlmBoxes
  const memo: typeof import('react').memo
  const mergeLabelMap: typeof import('./lib/compareLabelMap').mergeLabelMap
  const optimisticModelLoading: typeof import('./hooks/useModelEvents').optimisticModelLoading
  const optimisticModelUnloaded: typeof import('./hooks/useModelEvents').optimisticModelUnloaded
  const parseCategories: typeof import('./lib/parsers').parseCategories
  const processImageFiles: typeof import('./lib/processImageFiles').processImageFiles
  const renameTrainingJob: typeof import('./services/api').renameTrainingJob
  const request: typeof import('./services/request').request
  const saveFilterSettings: typeof import('./services/api').saveFilterSettings
  const startComparePrecompute: typeof import('./services/api').startComparePrecompute
  const startTraining: typeof import('./services/api').startTraining
  const startTransition: typeof import('react').startTransition
  const toast: typeof import('react-hot-toast').toast
  const tokenCache: typeof import('./lib/constants').tokenCache
  const unloadModel: typeof import('./services/api').unloadModel
  const unloadSam2: typeof import('./services/api').unloadSam2
  const unloadSam3: typeof import('./services/api').unloadSam3
  const uploadCache: typeof import('./lib/constants').uploadCache
  const uploadVideo: typeof import('./services/api').uploadVideo
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAntdTable: typeof import('ahooks').useAntdTable
  const useAsyncEffect: typeof import('ahooks').useAsyncEffect
  const useBatchDetection: typeof import('./hooks/useBatchDetection').useBatchDetection
  const useBoolean: typeof import('ahooks').useBoolean
  const useCallback: typeof import('react').useCallback
  const useClickAway: typeof import('ahooks').useClickAway
  const useCompareContext: typeof import('./components/Compare/CompareContext').useCompareContext
  const useCompareDataset: typeof import('./hooks/useCompareDataset').useCompareDataset
  const useContext: typeof import('react').useContext
  const useControllableValue: typeof import('ahooks').useControllableValue
  const useCookieState: typeof import('ahooks').useCookieState
  const useCountDown: typeof import('ahooks').useCountDown
  const useCounter: typeof import('ahooks').useCounter
  const useCreation: typeof import('ahooks').useCreation
  const useDebounce: typeof import('ahooks').useDebounce
  const useDebounceEffect: typeof import('ahooks').useDebounceEffect
  const useDebounceFn: typeof import('ahooks').useDebounceFn
  const useDebugValue: typeof import('react').useDebugValue
  const useDeepCompareEffect: typeof import('ahooks').useDeepCompareEffect
  const useDeepCompareLayoutEffect: typeof import('ahooks').useDeepCompareLayoutEffect
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeleteAllDetectionsMutation: typeof import('./hooks/useDetection').useDeleteAllDetectionsMutation
  const useDeleteDetectionMutation: typeof import('./hooks/useDetection').useDeleteDetectionMutation
  const useDetectMutation: typeof import('./hooks/useDetection').useDetectMutation
  const useDetectionAnnotation: typeof import('./hooks/useDetectionAnnotation').useDetectionAnnotation
  const useDetectionHistory: typeof import('./hooks/useDetectionHistory').useDetectionHistory
  const useDetectionListInfiniteQuery: typeof import('./hooks/useDetection').useDetectionListInfiniteQuery
  const useDetectionListQuery: typeof import('./hooks/useDetection').useDetectionListQuery
  const useDetectionProcess: typeof import('./hooks/useDetectionProcess').useDetectionProcess
  const useDetectionTimer: typeof import('./hooks/useDetectionTimer').useDetectionTimer
  const useDocumentVisibility: typeof import('ahooks').useDocumentVisibility
  const useDrag: typeof import('ahooks').useDrag
  const useDrop: typeof import('ahooks').useDrop
  const useDynamicList: typeof import('ahooks').useDynamicList
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEventEmitter: typeof import('ahooks').useEventEmitter
  const useEventListener: typeof import('ahooks').useEventListener
  const useEventTarget: typeof import('ahooks').useEventTarget
  const useExportBatchMutation: typeof import('./hooks/useDetection').useExportBatchMutation
  const useExternal: typeof import('ahooks').useExternal
  const useFavicon: typeof import('ahooks').useFavicon
  const useFocusWithin: typeof import('ahooks').useFocusWithin
  const useFullscreen: typeof import('ahooks').useFullscreen
  const useFusionTable: typeof import('ahooks').useFusionTable
  const useGetState: typeof import('ahooks').useGetState
  const useHistoryTravel: typeof import('ahooks').useHistoryTravel
  const useHover: typeof import('ahooks').useHover
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInViewport: typeof import('ahooks').useInViewport
  const useInfiniteQuery: typeof import('@tanstack/react-query').useInfiniteQuery
  const useInfiniteScroll: typeof import('ahooks').useInfiniteScroll
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInterval: typeof import('ahooks').useInterval
  const useIsomorphicLayoutEffect: typeof import('ahooks').useIsomorphicLayoutEffect
  const useKeyPress: typeof import('ahooks').useKeyPress
  const useLatest: typeof import('ahooks').useLatest
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLoadAll: typeof import('./hooks/useLoadAll').useLoadAll
  const useLocalStorageState: typeof import('ahooks').useLocalStorageState
  const useLockFn: typeof import('ahooks').useLockFn
  const useLongPress: typeof import('ahooks').useLongPress
  const useMap: typeof import('ahooks').useMap
  const useMemo: typeof import('react').useMemo
  const useMemoizedFn: typeof import('ahooks').useMemoizedFn
  const useModelEvents: typeof import('./hooks/useModelEvents').useModelEvents
  const useMount: typeof import('ahooks').useMount
  const useMouse: typeof import('ahooks').useMouse
  const useMutation: typeof import('@tanstack/react-query').useMutation
  const useMutationObserver: typeof import('ahooks').useMutationObserver
  const useNetwork: typeof import('ahooks').useNetwork
  const useOptimistic: typeof import('react').useOptimistic
  const usePagination: typeof import('ahooks').usePagination
  const usePrevious: typeof import('ahooks').usePrevious
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useQueryClient: typeof import('@tanstack/react-query').useQueryClient
  const useRafInterval: typeof import('ahooks').useRafInterval
  const useRafState: typeof import('ahooks').useRafState
  const useRafTimeout: typeof import('ahooks').useRafTimeout
  const useReactive: typeof import('ahooks').useReactive
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRequest: typeof import('ahooks').useRequest
  const useResetState: typeof import('ahooks').useResetState
  const useResponsive: typeof import('ahooks').useResponsive
  const useSafeState: typeof import('ahooks').useSafeState
  const useScroll: typeof import('ahooks').useScroll
  const useScrollLoad: typeof import('./hooks/useScrollLoad').useScrollLoad
  const useSelections: typeof import('ahooks').useSelections
  const useSessionStorageState: typeof import('ahooks').useSessionStorageState
  const useSet: typeof import('ahooks').useSet
  const useSetState: typeof import('ahooks').useSetState
  const useSize: typeof import('ahooks').useSize
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTextSelection: typeof import('ahooks').useTextSelection
  const useTheme: typeof import('./hooks/useTheme').useTheme
  const useThrottle: typeof import('ahooks').useThrottle
  const useThrottleEffect: typeof import('ahooks').useThrottleEffect
  const useThrottleFn: typeof import('ahooks').useThrottleFn
  const useTimeout: typeof import('ahooks').useTimeout
  const useTitle: typeof import('ahooks').useTitle
  const useToggle: typeof import('ahooks').useToggle
  const useTrackedEffect: typeof import('ahooks').useTrackedEffect
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
  const useUnmount: typeof import('ahooks').useUnmount
  const useUnmountedRef: typeof import('ahooks').useUnmountedRef
  const useUpdate: typeof import('ahooks').useUpdate
  const useUpdateEffect: typeof import('ahooks').useUpdateEffect
  const useUpdateLayoutEffect: typeof import('ahooks').useUpdateLayoutEffect
  const useVirtualList: typeof import('ahooks').useVirtualList
  const useVirtualizer: typeof import('@tanstack/react-virtual').useVirtualizer
  const useWebSocket: typeof import('ahooks').useWebSocket
  const useWhyDidYouUpdate: typeof import('ahooks').useWhyDidYouUpdate
  const useYoloValidation: typeof import('./hooks/useYoloValidation').useYoloValidation
  const vlmLabelsForGtClass: typeof import('./lib/compareLabelMap').vlmLabelsForGtClass
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CompareDatasetContextValue } from './hooks/useCompareDataset'
  import('./hooks/useCompareDataset')
  // @ts-ignore
  export type { ThemeMode, ThemeContextValue } from './hooks/useTheme'
  import('./hooks/useTheme')
  // @ts-ignore
  export type { ErrorBoundary } from './components/ErrorBoundary/index'
  import('./components/ErrorBoundary/index')
  // @ts-ignore
  export type { SidebarProps } from './components/Sidebar/index'
  import('./components/Sidebar/index')
  // @ts-ignore
  export type { CompareLabelMap } from './lib/compareLabelMap'
  import('./lib/compareLabelMap')
  // @ts-ignore
  export type { CaseFilterKind, CaseFilter } from './lib/compareReportCases'
  import('./lib/compareReportCases')
  // @ts-ignore
  export type { FilterMode } from './lib/filterBoxes'
  import('./lib/filterBoxes')
  // @ts-ignore
  export type { YoloSeries, ImportResult, ImportProgress, ChunkInitResult, CompareDataset, CompareImage, PrecomputeTaskStatus, DatasetImagesResponse, CompareBox, CompareAnnotationsResponse, ExportVlmDatasetResult, CompareReportMetrics, CompareReportClassStat, CompareReportSplitStat, CompareReportImageClassStat, CompareReportImageStat, CompareReportResponse } from './services/api'
  import('./services/api')
  // @ts-ignore
  export type { BBox, Detection, DetectResponse, TrainingJob, KeyFrame, VideoInfo, ListResponse } from './types/index'
  import('./types/index')
}
